
abstract class AppStringBase {
  late String appName;

  //####################### 系统按钮 ##############################
  late String appButtonOk;
  late String appButtonCancel;
  late String appButtonDelete;
  late String appButtonCache;
  late String appButtonFatten;
  late String appButtonTop;
  late String appButtonUnTop;
  late String appButtonBack;
  late String appButtonClear;
  late String appButtonEdit;
  late String appButtonQrCode;
  late String appButtonMove;
  late String appButtonDetail;
  late String appButtonChoose;
  late String appButtonRename;
  late String appListModel;
  late String appGroupModel;
  late String appGridModel;
  late String appAddYes;
  late String appAddNo;
  late String appButtonStart;
  late String appButtonStop;
  late String appButtonPause;
  late String appButtonPlay;
  late String appButtonDisable;
  late String appButtonDisabled;
  late String appButtonEnable;
  late String appButtonReversal;
  late String appButtonCopy;

  //####################### 下拉刷新 ##############################
  late String appPullRefresh;
  late String appPullRefreshRelease;
  late String appPullRefreshing;
  late String appPullRefreshFinish;
  late String appPullRefreshFailed;
  late String appPullLoad;
  late String appPullLoadRelease;
  late String appPullLoading;
  late String appPullLoadFinish;
  late String appPullLoadFailed;
  late String appPullUpdateAt;
  late String appPullNoMore;

  //####################### 消息 ##############################
  late String msgExit;
  late String msgCollectionExist;
  late String msgCollectionSuccess;
  late String msgCleanCache;
  late String msgBookNotExist;
  late String msgNoData;
  late String msgDetail;
  late String msgView;
  late String msgInput;
  late String msgRestoreConfig;
  late String msgRestoreConfigSuccess;
  late String msgSearchInput;
  late String msgErrorUnknown;
  late String msgNoticeTitle;
  late String msgNotSelectBookSource;
  late String msgBookShelfAdd;
  late String msgBookShelfRemove;
  late String msgBookChapterUnLoadFinish;
  late String msgUrlError;
  late String msgAddToBookShelf;
  late String msgAddDownload;
  late String msgCopySuccess;
  late String msgUpdateChapter;
  late String msgUpdateChapterHasNew;
  late String msgUpdateChapterNotNew;
  late String msgUpdateChapterSuccess;
  late String msgUpdateChapterFail;
  late String msgBookMarkAdd;
  late String msgBookMarkRemove;
  late String msgBookContentSearch;
  late String msgBookContentSearchNothing;
  late String msgFileReadError;
  late String msgFileCacheNotExist;
  late String msgFileUnLoad;
  late String msgLoadUnFinish;
  late String msgLoadNoNextPage;
  late String msgChapterReadFinish;
  late String msgChapterFinish;
  late String msgBookLoading;
  late String msgBookLoadError;
  late String msgBookLoadEmpty;
  late String msgBookLoadCatalog;
  late String msgBookLoadChangeSource;
  late String msgGetBookFail;
  late String msgLocal;
  late String msgLocalHasImport;
  late String msgLocalImportSuccess;
  late String msgLocalImportFail;
  late String msgLocalImportChoose;
  late String msgLocalNoDetail;
  late String msgBookSourceRuleEmpty;
  late String msgBookFilterRuleEmpty;
  late String msgBookDownloadEmpty;
  late String msgClearNetworkCache;
  late String msgBookSourceDel;

  //####################### 网络 ##############################
  late String networkError;
  late String networkError_401;
  late String networkError_403;
  late String networkError_404;
  late String networkErrorTimeout;
  late String networkErrorGetData;
  late String networkNotUse;

  //####################### 字典 ##############################
  late String dictThemeTitle;
  late String dictTheme_1;
  late String dictTheme_2;
  late String dictSortTitle;
  late String dictSort_1;
  late String dictSort_2;
  late String dictSort_3;
  late String dictGenderTitle;
  late String dictGender_1;
  late String dictGender_2;
  late String dictLocaleTitle;
  late String dictLocale_1;
  late String dictLocale_2;
  late String dictLocale_3;
  late String dictBookshelfModelTitle;
  late String dictBookshelfModel_1;
  late String dictBookshelfModel_2;
  late String dictBookSourceFilterModelTitle;
  late String dictBookSourceFilterModel_1;
  late String dictBookSourceFilterModel_2;
  late String dictVoice_1;
  late String dictVoice_2;
  late String dictVoice_3;
  late String dictBookSourceSort_1;
  late String dictBookSourceSort_2;
  late String dictBookSourceSort_3;
  late String dictBookSourceSort_4;

  //####################### tab ##############################
  late String homeTab_1;
  late String homeTab_2;
  late String homeTab_3;

  //####################### 书架 ##############################
  late String bookshelfMenuImportLocal;
  late String bookshelfMenuClearUp;
  late String bookshelfMsgNoData;
  late String bookshelfMenuNewGroup;
  late String bookshelfMenuDownload;
  late String bookshelfMenuWeb;
  late String bookshelfMsgGroup;
  late String bookshelfMsgBookNum;
  late String bookshelfGroup;
  late String bookshelfGroupInputTitle;
  late String bookshelfGroupNameLen;
  late String bookshelfGroupSelectTitle;
  late String bookshelfGroupMsgSuccess;
  late String bookshelfHasRead;

  //********************** 书籍搜索 ***************************
  late String bookSearchType;
  late String bookSearchType1;
  late String bookSearchType2;
  late String bookSearchType3;
  late String bookSearchNotice1;
  late String bookSearchNotice2;
  late String bookSearchNotice3;
  late String bookSearchHistory;
  late String bookSearchAllBookSource;
  late String bookSearchAllBookSourceGroup;
  late String bookSearchSourceList;
  late String bookSearchSourceGroup;
  late String bookSearchSourceListTitle;
  late String bookSearchSourceGroupTitle;
  late String bookSearchFilterType;
  late String bookSearchFilterSource;

  //********************** 书籍详情 ***************************
  late String bookDetailMenuReload;
  late String bookDetailMenuChange;
  late String bookDetailTitleIntro;
  late String bookDetailTitleBookSource;
  late String bookDetailTitleChapter;
  late String bookDetailBtnAdd;
  late String bookDetailBtnRemove;
  late String bookDetailBtnRead;
  late String bookDetailMsgAuthorName;
  late String bookDetailMsgAuthor;
  late String bookDetailMsgUnknown;
  late String bookDetailMsgLastChapter;
  late String bookDetailMsgBookSourceCurrent;
  late String bookDetailMsgBookSourceMore;
  late String bookDetailMsgUpdateTime;
  late String bookDetailMsgChapterAll;
  late String bookDetailMsgBookSource;
  late String bookDetailMsgTotal;
  late String bookDetailMsgTotalBookSource;
  late String bookDetailMsgSpeed;
  late String bookDetailMsgSpeedTime;
  late String bookDetailMsgSpeedTest;
  late String bookDetailMsgTotalChapter;
  late String bookDetailMsgOther;
  late String bookDetailMsgSourceNum;
  late String bookDetailMsgChapterNum;
  late String bookDetailMsgFrom;
  late String bookDetailMsgSource;
  late String bookDetailMsgChapterCache;
  late String bookDetailMsgCurrentChapter;
  late String bookDetailMsgUpdate;

  //********************** 书籍阅读 ***************************
  late String readMenuDetail;
  late String readMenuAddBookMarks;
  late String readMenuRemoveBookMarks;
  late String readMenuSetEncode;
  late String readMenuCopyPage;
  late String readMenuCopyChapter;
  late String readMenuRefreshChapter;
  late String readMenuSearchAll;
  late String readMenuBtnPre;
  late String readMenuBtnNext;
  late String readMenuBtnChapter;
  late String readMenuBtnBookMark;
  late String readMenuBtnSource;
  late String readMenuBtnCache;
  late String readMenuBtnUI;
  late String readMenuBtnOther;
  late String readMenuBtnFont;
  late String readMenuBtnCustom;
  late String readMenuBtnPage;
  late String readMenuBtnPage1;
  late String readMenuBtnPage2;
  late String readMenuBtnPage3;
  late String readMenuBtnPage4;
  late String readMenuBtnPage5;
  late String readMenuBtnPage6;
  late String readMenuBtnPage7;
  late String readCacheTitle;
  late String readCacheBtn1;
  late String readCacheBtn2;
  late String readCacheBtn3;
  late String readTopTitle;
  late String readMenuUiBrightness;
  late String readMenuUIFont;
  late String readMenuUICustom;
  late String readMenuUIDisplay;
  late String readMenuUIDisplay1;
  late String readMenuUIDisplay2;
  late String readMenuUIDisplay3;
  late String readMenuUILanguage;
  late String readMenuUILanguage1;
  late String readMenuUILanguage2;
  late String readMenuUILanguage3;
  late String readMenuGlobalClick;
  late String readMenuPageTurnScope;
  late String readMenuMoreSetting;
  late String readMenuFontMargin1;
  late String readMenuFontMargin2;
  late String readMenuFontMargin3;
  late String readMenuFontMargin4;
  late String readMenuFontMargin5;
  late String readMenuFontMargin6;
  late String readMenuFontMargin7;
  late String readMenuFontColor1;
  late String readMenuFontColor2;
  late String readMenuFontColor3;
  late String readMenuFontColorName;
  late String readMenuFontColorThemeDel;
  late String readMenuFontColorDel;
  late String readMenuNotice1;
  late String readMenuNotice2;
  late String readMenuNotice3;
  late String readMenuNoticeInfo;
  late String readMenuNoticeBtn1;
  late String readMenuNoticeBtn2;
  late String readMenuAutoPageRate;
  late String readMenuAutoPageRateMin;
  late String readMenuAutoPageRateAdd;
  late String readMenuAutoPageExit;
  late String readMenuReadAloudLocal;
  late String readMenuReadAloudNotSupport;
  late String readMenuReadAloudChoose;
  late String readMenuReadAloudMinute;
  late String readMenuReadAloudRate;
  late String readMenuReadAloudVoice;
  late String readMenuReadAloudVoice1;
  late String readMenuReadAloudVoice2;
  late String readMenuReadAloudTiming;
  late String readMenuReadAloudExist;

  //********************** 更多设置 ***************************
  late String bookMoreSettingTitle;
  late String bookMoreSettingBold;
  late String bookMoreSettingIndent;
  late String bookMoreSettingIndent1;
  late String bookMoreSettingIndent2;
  late String bookMoreSettingIndent3;
  late String bookMoreSettingIndent4;
  late String bookMoreSettingIndent5;
  late String bookMoreSettingTimeout;
  late String bookMoreSettingTimeout1;
  late String bookMoreSettingTimeout2;
  late String bookMoreSettingTimeout3;
  late String bookMoreSettingTimeout4;
  late String bookMoreSettingTimeout5;
  late String bookMoreSettingTimeout6;
  late String bookMoreSettingTimeout7;
  late String bookMoreSettingStatusBar;
  late String bookMoreSettingHomeIndicator;
  late String bookMoreSettingShowTitle;
  late String bookMoreSettingShowTime;
  late String bookMoreSettingShowBattery;
  late String bookMoreSettingShowPage;
  late String bookMoreSettingShowProcess;
  late String bookMoreSettingShowChapterIndex;

  //********************** 选择书籍来源 ***************************
  late String selectBookSourceTitle;
  late String selectBookSourceCurrent;
  late String selectBookSourceTmp;

  //********************** 选择书籍来源 ***************************
  late String bookFontTitle;
  late String bookFont1;
  late String bookFont2;
  late String bookFont3;
  late String bookFont4;
  late String bookFont5;

  //####################### 书城 ##############################
  late String bookFindEmpty;
  late String bookChooseEmpty;

  //####################### 设置 ##############################
  late String settingMenuBookSource;
  late String settingMenuBookFilter;
  late String settingMenuBookThread;
  late String settingMenuBookDownload;
  late String settingMenuOther;
  late String settingMenuBookImport;
  late String settingMenuBookShowType;
  late String settingMenuBookSort;
  late String settingMenuBookStart;
  late String settingMenuBookRefresh;
  late String settingMenuAutoDownloadChapter;
  late String settingMenuReplaceEnableDefault;
  late String settingMenuBookTheme;
  late String settingMenuBookLanguage;
  late String settingMenuBookSourceFilter;
  late String settingMenuBookCache;
  late String settingMenuBookBackup;
  late String settingMenuBookAbout;
  late String settingMenuVersion;
  late String settingMenuWebPort;
  late String settingMenuInputWebPort;
  late String settingMenuWebPortError;
  late String settingMenuBookSourceSore;
  late String settingMenuNetworkCache;
  late String settingMenuReward;

  //********************** 书源管理 ***************************
  late String bookSourceMenu;
  late String bookSourceGroup;
  late String bookSourceQrCodeSelect;
  late String bookSourceSearchHint;
  late String bookSourceUnNameGroup;
  late String bookSourceMenuDefault;
  late String bookSourceMenuAdd;
  late String bookSourceMenuEdit;
  late String bookSourceMenuImportLocal;
  late String bookSourceMenuImportNetwork;
  late String bookSourceMenuImportQrCode;
  late String bookSourceMenuGenQrCode;
  late String bookSourceMenuReversalSelect;
  late String bookSourceMenuExportSelect;
  late String bookSourceMenuDeleteSelect;
  late String bookSourceMenuCheckSelect;
  late String bookSourceExist;
  late String bookSourceExistPart;
  late String bookSourceInputTitle;
  late String bookSourceAddSuccess;
  late String bookSourceUpdateSuccess;
  late String bookSourceSaveSuccess;
  late String bookSourceErrorLocal;
  late String bookSourceErrorNetwork;
  late String bookSourceErrorQrCode;

  //********************** 书源编辑 ***************************
  late String bookSourceEditBase;
  late String bookSourceEditName;
  late String bookSourceEditUrl;
  late String bookSourceEditGroup;
  late String bookSourceEditEnable;
  late String bookSourceEditSearchForDetail;

  late String bookSourceEditFind;
  late String bookSourceEditFindUrl;
  late String bookSourceEditFindList;
  late String bookSourceEditFindName;
  late String bookSourceEditFindAuthor;
  late String bookSourceEditFindKind;
  late String bookSourceEditFindLastChapter;
  late String bookSourceEditFindIntroduce;
  late String bookSourceEditFindCoverUrl;
  late String bookSourceEditFindNoteUrl;

  late String bookSourceEditSearch;
  late String bookSourceEditSearchUrl;
  late String bookSourceEditBookUrlPattern;
  late String bookSourceEditSearchList;
  late String bookSourceEditSearchName;
  late String bookSourceEditSearchAuthor;
  late String bookSourceEditSearchKind;
  late String bookSourceEditSearchLastChapter;
  late String bookSourceEditSearchIntroduce;
  late String bookSourceEditSearchCoverUrl;
  late String bookSourceEditSearchNoteUrl;

  late String bookSourceEditDetail;
  late String bookSourceEditDetailInfoInit;
  late String bookSourceEditDetailName;
  late String bookSourceEditDetailAuthor;
  late String bookSourceEditDetailKind;
  late String bookSourceEditDetailLastChapter;
  late String bookSourceEditDetailIntroduce;
  late String bookSourceEditDetailCoverUrl;
  late String bookSourceEditDetailChapterUrl;

  late String bookSourceEditChapter;
  late String bookSourceEditDetailChapterUrlNext;
  late String bookSourceEditDetailChapterList;
  late String bookSourceEditDetailChapterName;
  late String bookSourceEditContentUrl;

  late String bookSourceEditContent;
  late String bookSourceEditContentRule;
  late String bookSourceEditContentUrlNext;

  late String bookSourceEditOther;
  late String bookSourceEditOtherSerialNumber;
  late String bookSourceEditOtherWeight;
  late String bookSourceEditOtherType;
  late String bookSourceEditOtherLogin;
  late String bookSourceEditOtherAgent;

  late String bookSourceEditNoticeName;
  late String bookSourceEditNoticeUrl;

  //********************** 书源调试 ***************************
  late String bookSourceDebugTitle;

  //********************** 内容过滤 ***************************
  late String bookFilterMenu;
  late String bookFilterMenuDefault;
  late String bookFilterMenuAdd;
  late String bookFilterMenuEdit;
  late String bookFilterInputTitle;
  late String bookFilterExist;
  late String bookFilterExistPart;
  late String bookFilterErrorLocal;
  late String bookFilterErrorNetwork;

  //********************** 内容过滤规则编辑 ***************************
  late String bookFilterEditReplaceSummary;
  late String bookFilterEditRegex;
  late String bookFilterEditIsRegex;
  late String bookFilterEditReplacement;
  late String bookFilterEditUseTo;
  late String bookFilterEditReplaceSummaryNotice;
  late String bookFilterEditRegexNotice;
  late String bookFilterEditReplacementNotice;
  late String bookFilterUpdateSuccess;
  late String bookFilterSaveSuccess;

  //********************** 线程管理 ***************************
  late String threadNumSearch;
  late String threadNumBookShelf;
  late String threadNumBookSource;
  late String threadNumDetail;
  late String threadNumChapter;
  late String threadNumContent;

  //********************** 下载任务 ***************************
  late String bookDownload1;
  late String bookDownload2;
  late String bookDownload3;
  late String bookDownload4;

  //********************** 书籍缓存 ***************************
  late String bookCacheSize;

  //********************** web服务 ***************************
  late String webServerTitle;
  late String webServerInfo1;
  late String webServerInfo2;
  late String webServerInfo3;
  late String webServerInfo4;
  late String webServerStart;
  late String webServerStop;

  //********************** 广告设置 ***************************
  late String adConfig;
  late String adConfigOpen;

  //********************** 关于&帮助 ***************************
  late String aboutToShare;
  late String aboutToHelp;
  late String aboutToPrivacy;
  late String aboutToDisclaimer;
  late String aboutToMe;

  //********************** 激励去广告 ***************************
  late String rewardTime;
  late String rewardDesc;
  late String rewardDescInfo1;
  late String rewardDescInfo2;
  late String rewardButton;
  late String rewardButtonView;
}
